### ISSUE TITLE
Migrate Information from Google Doc to Wiki

### ISSUE THREAD

**Issue by nickchan2** [angry-goose-initiative/wiki#1]
The [wiki](https://github.com/angry-goose-initiative/wiki/wiki) is now the central place where we keep AGI information. We need to move relevant info from the [Google Doc](https://docs.google.com/document/d/1HeZ4l5OxooQuh2kdJ1o-uWJXWzGPsVntSPlf_ByFmWA/edit?usp=sharing) to it.

**Comment by JZJisawesome** [comment]
Agreed. We should afterwards still keep the google doc around in a read-only state for future reference.

**Comment by JZJisawesome** [comment]
I think I moved everything that's mine from the google doc, so I'll remove myself as assignee :)
