### ISSUE TITLE
Code cleanup in IRVE

### ISSUE THREAD

**Issue by nickchan2** [angry-goose-initiative/wiki#16]
- Removing redundant namespaces
- Use `constexpr` instead of `#define` when possible
- Use `consteval` where possible
- Switch Class, struct, etc. names to PascalCase and ditch `_t`
- Use C++ style casts instead of C-style
- Remove completely pointless comments
- All files snake case
- Avoid using macros (they're usually not a good practice)
- Use `#pragma once` in headers
- Remove file name from file headers
- Remove redundant comments
- Make things more strongly typed
- Using anonymous namespaces instead of static for internal linkage

**Comment by JZJisawesome** [comment]
Also switching to #pragma once given we no longer support MSVC would be cool

**Comment by JZJisawesome** [comment]
With the recently merged Word improvements (thanks Nick!) I think we're done!

I'll move this to the review section of the AGI Kanban, feel free to close Nick (unless you think we should make additional changes, then we can move it back to the In progress section) :)

**Comment by nickchan2** [comment]
There's a bit more left for this, there's still a small amount of the changes from the PR that we didn't merge that I want to get in (some naming wasn't fixed and header guards needed to be changed)
