### ISSUE TITLE
Make it more clear in other AGI projects' readmes why issues are disabled

### ISSUE THREAD

**Issue by JZJisawesome** [angry-goose-initiative/wiki#17]
Since they are all collected in the wiki repo instead

**Comment by JZJisawesome** [comment]
Or should we allow for issues from multiple projects given that everything is combined in the AGI Kanban anyways?

**Comment by nickchan2** [comment]
I think everything should be in wiki since an issue can pertain to multiple repos in the organization

**Comment by JZJisawesome** [comment]
Agreed.

I left an issue in each of the other repos pointing towards this one.

Closing!
