### ISSUE TITLE
LETC: Bus protocol selection

### ISSUE THREAD

**Issue by JZJisawesome** [angry-goose-initiative/wiki#18]
AXI, LIMP, ABP, AHB, or Wishbone?

We will at least need a bridge to AXI in order to communicate with the PS.

Regardless of what we do the latency will be high. Likely a L1 cache is necessary?

**Comment by nickchan2** [comment]
As discussed yesterday, we are leaning towards an L1 cache and using AXI

**Comment by JZJisawesome** [comment]
LETC Matrix planning has begun here: https://github.com/angry-goose-initiative/wiki/wiki/LETC-Matrix
