### ISSUE TITLE
Fix or remove Makefile

### ISSUE THREAD

**Issue by nickchan2** [angry-goose-initiative/wiki#25]
The Makefile at the root of irve no longer works and should be fixed or removed. I'm leaning towards removing it. @JZJisawesome  Thoughts?

**Comment by JZJisawesome** [comment]
Agreed, I will remove it :)

**Comment by JZJisawesome** [comment]
Removed in commit 5628327f29d9eba2707b2172dc8f04747edde370.

I will close this ticket the next time my branch is merged to staging
