### ISSUE TITLE
Two UARTs

### ISSUE THREAD

**Issue by nickchan2** [angry-goose-initiative/wiki#4]
We want LETC to have two UARTs, one for Conductor, and the other for RISC-V software. We need to figure out the best way to achieve this.

**Comment by JZJisawesome** [comment]
As Nick and I have discussed the plan at the moment is to use UART0 for Conductor and UART1 for RISC-V software on LETC.

The remaining issue is the inability to route UART1 interrupts from the peripheral to the PL (it can only go to the ARM core). This may however not be a requirement of the Linux kernel

See here for more info:
https://github.com/angry-goose-initiative/wiki/wiki/LETC-Architecture-Overview

**Comment by JZJisawesome** [comment]
No longer an issue as we've confirmed we can route interrupts from UART1 to the fabric.
