### ISSUE TITLE
Find a better way to keep the wiki homepage and org readme in sync

### ISSUE THREAD

**Issue by JZJisawesome** [angry-goose-initiative/wiki#40]

**Comment by nickchan2** [comment]
Our general philosophy is to keep info in the wiki and avoid duplication, why not just link readme's to relevant wiki pages?

**Comment by JZJisawesome** [comment]
Definitely. That's a good idea for the various AGI projects (and I've already begun to do this for LETC, linking to the guides on the wiki).

The only thing is that for the front-page of the AGI organization it would be nice to be able to display info at a glance (because it's the first thing people will see, so it reduces the clicks it takes for them to get to the intro page).

This is kind of a micro-optimization though and possibly not worth it.

Let me know what you think: we could just put it back to just being a link to the main wiki page :)

**Comment by JZJisawesome** [comment]
Just doing it manually for the org page. Not a big deal.
